export default interface SireneUniteLegaleDto {
    siren: string;
    statutDiffusionUniteLegale: string;
    unitePurgeeUniteLegale: string | "";
    dateCreationUniteLegale: string;
    sigleUniteLegale: string | "";
    sexeUniteLegale: string | "";
    prenom1UniteLegale: string | "";
    prenom2UniteLegale: string | "";
    prenom3UniteLegale: string | "";
    prenom4UniteLegale: string | "";
    prenomUsuelUniteLegale: string | "";
    pseudonymeUniteLegale: string | "";
    identifiantAssociationUniteLegale: string | "";
    trancheEffectifsUniteLegale: string | "";
    anneeEffectifsUniteLegale: string | null;
    dateDernierTraitementUniteLegale: string | "";
    nombrePeriodesUniteLegale: string | "";
    categorieEntreprise: string | "";
    anneeCategorieEntreprise: string | "";
    dateDebut: string | "";
    etatAdministratifUniteLegale: string | "";
    nomUniteLegale: string | "";
    nomUsageUniteLegale: string | "";
    denominationUniteLegale: string | "";
    denominationUsuelle1UniteLegale: string | "";
    denominationUsuelle2UniteLegale: string | "";
    denominationUsuelle3UniteLegale: string | "";
    categorieJuridiqueUniteLegale: string;
    activitePrincipaleUniteLegale: string | "";
    nomenclatureActivitePrincipaleUniteLegale: string | "";
    nicSiegeUniteLegale: string | "";
    economieSocialeSolidaireUniteLegale: string | "";
    societeMissionUniteLegale: string | "";
    caractereEmployeurUniteLegale: string | "";
}
