import { ApplicationFlatDto, ApplicationStatus, ApplicationNature, PaymentFlatDto } from "dto";

export const APPLICATION_DTO_EXAMPLE: ApplicationFlatDto = {
    idUnique: "string",
    idJointure: "string",
    ej: "1234567890",
    idVersement: "id-versement-1234",
    descriptionIdJointure: "string",
    nomAttribuant: "Nom attribuant",
    typeIdAttribuant: "siret",
    idAttribuant: "50000000000055",
    nomAutoriteGestion: "string",
    nomServiceInstructeur: "Service instructeur",
    idServiceInstructeur: "30000000000033",
    typeIdServiceInstructeur: "siret",
    idAutoriteGestion: "N/A",
    typeIdAutoriteGestion: "N/A",
    typeIdEtablissementBeneficiaire: "siret",
    idEtablissementBeneficiaire: "10000000000012",
    typeIdEntrepriseBeneficiaire: "siren",
    idEntrepriseBeneficiaire: "123456789",
    fournisseur: "provider slug",
    dateMiseAJour: "2025-01-15T00:00:00.000Z",
    idSubvention: "lca-123456789-2023-001",
    idSubventionProvider: "123456789",
    statutLabel: ApplicationStatus.GRANTED,
    pluriannualite: false,
    anneesPluriannualite: "N/A",
    anneeDemande: null,
    dateDecision: "2024-02-23T00:00:00.000Z",
    dateDepotDemande: "2024-01-15T00:00:00.000Z",
    dateConvention: "N/A",
    referenceDecision: "string",
    dispositif: "string",
    sousDispositif: "string",
    objet: "objet",
    nature: ApplicationNature.MONEY,
    conditionsVersements: "N/A",
    descriptionConditionsVersements: "N/A",
    datesPeriodeVersement: "N/A",
    cofinancementsSollicites: false,
    nomsAttribuantsCofinanceurs: [],
    typeIdCofinanceursSollicites: "N/A",
    idCofinanceursSollicites: [],
    idRAE: "N/A",
    notificationUE: false,
    pourcentageSubvention: 100,
    montantTotal: 20000,
    montantDemande: 20000,
    montantAccorde: 15000,
    exerciceBudgetaire: 2023,
};

export const PAYMENT_DTO_EXAMPLE: PaymentFlatDto = {
    idUnique: "string",
    typeIdEtablissementBeneficiaire: "siret",
    idEtablissementBeneficiaire: "10000000000012",
    typeIdEntrepriseBeneficiaire: "siren",
    idEntrepriseBeneficiaire: "123456789",
    fournisseur: "provider",
    dateMiseAJour: "2024-01-15T00:00:00.000Z",
    idVersement: "id-versement-1234",
    exerciceBudgetaire: 2023,
    montant: 15000,
    dateOperation: new Date("2023-06-30"),
    codeCentreFinancier: "163-DRAJES",
    libelleCentreFinancier: "DRAJES Île-de-France",
    attachementComptable: "N/A",
    regionAttachementComptable: "11",
    ej: "1234567890",
    programme: "Jeunesse et vie associative",
    numeroProgramme: "163",
    mission: "Sport, jeunesse et vie associative",
    ministere: "Ministère des Sports",
    sigleMinistere: "MS",
    codeAction: null,
    action: null,
    codeActivite: null,
    activite: null,
};
