import { ObjectId } from "mongodb";
import Siren from "../../../../identifier-objects/Siren";
import Siret from "../../../../identifier-objects/Siret";
import { SireneEtablissementDbo } from "../@types/SireneEtablissementDbo";
import SireneEtablissementDto from "../@types/SireneEtablissementDto";
import { SireneEtablissementEntity } from "../../../../entities/SireneEtablissementEntity";

export const SIRENE_ETABLISSEMENT_DTO: SireneEtablissementDto = {
    siren: "123456789",
    nic: "00012",
    siret: "12345678900012",
    statutDiffusionEtablissement: "O",
    dateCreationEtablissement: new Date("2000-01-01"),
    trancheEffectifsEtablissement: "NN",
    anneeEffectifsEtablissement: 2023n,
    activitePrincipaleRegistreMetiersEtablissement: "",
    dateDernierTraitementEtablissement: new Date("2026-07-01T09:39:16"),
    etablissementSiege: true,
    nombrePeriodesEtablissement: 3n,
    complementAdresseEtablissement: "",
    numeroVoieEtablissement: "1",
    indiceRepetitionEtablissement: "",
    dernierNumeroVoieEtablissement: "",
    indiceRepetitionDernierNumeroVoieEtablissement: "",
    typeVoieEtablissement: "RUE",
    libelleVoieEtablissement: "DE LA PAIX",
    codePostalEtablissement: "75001",
    libelleCommuneEtablissement: "PARIS",
    libelleCommuneEtrangerEtablissement: "",
    distributionSpecialeEtablissement: "",
    codeCommuneEtablissement: "75101",
    codeCedexEtablissement: "",
    libelleCedexEtablissement: "",
    codePaysEtrangerEtablissement: "",
    libellePaysEtrangerEtablissement: "",
    identifiantAdresseEtablissement: "75101_0001",
    coordonneeLambertAbscisseEtablissement: "",
    coordonneeLambertOrdonneeEtablissement: "",
    complementAdresse2Etablissement: "",
    numeroVoie2Etablissement: "",
    indiceRepetition2Etablissement: "",
    typeVoie2Etablissement: "",
    libelleVoie2Etablissement: "",
    codePostal2Etablissement: "",
    libelleCommune2Etablissement: "",
    libelleCommuneEtranger2Etablissement: "",
    distributionSpeciale2Etablissement: "",
    codeCommune2Etablissement: "",
    codeCedex2Etablissement: "",
    libelleCedex2Etablissement: "",
    codePaysEtranger2Etablissement: "",
    libellePaysEtranger2Etablissement: "",
    dateDebut: new Date("2024-01-01"),
    etatAdministratifEtablissement: "A",
    enseigne1Etablissement: "",
    enseigne2Etablissement: "",
    enseigne3Etablissement: "",
    denominationUsuelleEtablissement: "ETABLISSEMENT TEST",
    activitePrincipaleEtablissement: "94.99Z",
    nomenclatureActivitePrincipaleEtablissement: "NAFRev2",
    caractereEmployeurEtablissement: "N",
    activitePrincipaleNAF25Etablissement: "",
};

export const SIRENE_ETABLISSEMENT_ENTITY: SireneEtablissementEntity = {
    siren: new Siren(SIRENE_ETABLISSEMENT_DTO.siren),
    nic: SIRENE_ETABLISSEMENT_DTO.nic,
    siret: new Siret(SIRENE_ETABLISSEMENT_DTO.siret),
    etablissementSiege: SIRENE_ETABLISSEMENT_DTO.etablissementSiege,
    numeroVoieEtablissement: SIRENE_ETABLISSEMENT_DTO.numeroVoieEtablissement,
    typeVoieEtablissement: SIRENE_ETABLISSEMENT_DTO.typeVoieEtablissement,
    libelleVoieEtablissement: SIRENE_ETABLISSEMENT_DTO.libelleVoieEtablissement,
    codePostalEtablissement: SIRENE_ETABLISSEMENT_DTO.codePostalEtablissement,
    libelleCommuneEtablissement: SIRENE_ETABLISSEMENT_DTO.libelleCommuneEtablissement,
    codeCommuneEtablissement: SIRENE_ETABLISSEMENT_DTO.codeCommuneEtablissement,
    codePaysEtrangerEtablissement: SIRENE_ETABLISSEMENT_DTO.codePaysEtrangerEtablissement,
    libellePaysEtrangerEtablissement: SIRENE_ETABLISSEMENT_DTO.libellePaysEtrangerEtablissement,
};

export const SIRENE_ETABLISSEMENT_DBO: SireneEtablissementDbo = {
    ...SIRENE_ETABLISSEMENT_ENTITY,
    _id: new ObjectId(),
    siren: SIRENE_ETABLISSEMENT_DTO.siren,
    siret: SIRENE_ETABLISSEMENT_DTO.siret,
};
