export enum NotificationType {
    TEST_EMAIL,
    USER_CREATED,
    USER_DELETED,
    USER_UPDATED,
    USER_ACTIVATED,
    USER_FORGET_PASSWORD,
    USER_LOGGED,
    USER_ALREADY_EXIST,
    USER_CONFLICT,
    SIGNUP_BAD_DOMAIN,
    FAILED_CRON,
}
