root: true
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
    - "plugin:svelte/recommended"
    - "plugin:vitest/recommended"
    - "plugin:vitest-globals/recommended"
    - prettier
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
    - import
    - vitest
parserOptions:
    sourceType: module
    ecmaVersion: 2020
    extraFileExtensions:
        - .svelte
env:
    browser: true
    es2017: true
    node: true
overrides:
    - files:
          - "*.svelte"
      parser: svelte-eslint-parser
      parserOptions:
          parser: "@typescript-eslint/parser"
    - files:
        - "**/*.test.{j,t}s?(x)"
        - "**/*.spec.{j,t}s?(x)"
      env:
        "vitest-globals/env": true
      globals:
        vi: true
rules:
    import/order: error
    "@typescript-eslint/no-unused-vars":
        - "warn"
        - destructuredArrayIgnorePattern: "^_"
          argsIgnorePattern: "^_"
          varsIgnorePattern: "^_"
#ignorePatterns:
#    - "*.test.ts"
#    - "*.spec.ts"
#    - node_modules
#    - webpack.*
#    - views/index.js
