export const AGENT_ETAT_DOMAIN = [
    "ac-aix-marseille.fr",
    "ac-amiens.fr",
    "ac-besancon.fr",
    "ac-bordeaux.fr",
    "ac-clermont.fr",
    "ac-corse.fr",
    "ac-creteil.fr",
    "ac-dijon.fr",
    "ac-grenoble.fr",
    "ac-guadeloupe.fr",
    "ac-lille.fr",
    "ac-limoges.fr",
    "ac-lyon.fr",
    "ac-martinique.fr",
    "ac-martinique.fr",
    "ac-mayotte.fr",
    "ac-montpellier.fr",
    "ac-nancy-metz.fr",
    "ac-nantes.fr",
    "ac-nice.fr",
    "ac-normandie.fr",
    "ac-orleans-tours.fr",
    "ac-paris.fr",
    "ac-poitiers.fr",
    "ac-reims.fr",
    "ac-rennes.fr",
    "ac-reunion.fr",
    "ac-strasbourg.fr",
    "ac-toulouse.fr",
    "ac-versailles.fr",
    "agencedusport.fr",
    "fonjep.org",
    "gouv.fr",
    "gouv.nc",
    "region-academique-auvergne-rhone-alpes.fr",
    "region-academique-bourgogne-franche-comte.fr",
    "region-academique-grand-est.fr",
    "region-academique-hauts-de-france.fr",
    "region-academique-idf.fr",
    "region-academique-nouvelle-aquitaine.fr",
    "region-academique-occitanie.fr",
    "region-academique-ocitanie.fr",
    "region-academique-paca.fr",
    "stjs.wf"
]

export const COLLECTIVITE_DOMAIN = [
    "rhone.fr"
]

export const ACCEPTED_EMAIL_DOMAIN = [...AGENT_ETAT_DOMAIN, ...COLLECTIVITE_DOMAIN]