export default interface IFonjepIndexedInformations {
    updated_at: Date,
    unique_id: string,
    montant_paye: number,
    status: string,
    service_instructeur: string,
    annee_demande: number,
    date_fin_triennale: Date,
    type_post: string,
    ville: string,
    code_postal?: string,
    contact: string,
    co_financeur?: string,
    co_financeur_contact?: string,
    co_financeur_siret?: string,
    co_financeur_montant?: number,
}
