env:
  jest: true
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - import
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - prettier
ignorePatterns:
  - "*.test.ts"
  - "*.spec.ts"
  - node_modules
rules:
  import/order: error
  "@typescript-eslint/no-unused-vars":
    - "warn"
    -  varsIgnorePattern: "^_"
