export interface UniteLegalHistoryRow {
    activitePrincipaleUniteLegale: string;
    caractereEmployeurUniteLegale: "O" | "N" | null;
    categorieJuridiqueUniteLegale: number;
    changementActivitePrincipaleUniteLegale: "true" | "false";
    changementCaractereEmployeurUniteLegale: "true" | "false";
    changementCategorieJuridiqueUniteLegale: "true" | "false";
    changementDenominationUniteLegale: "true" | "false";
    changementDenominationUsuelleUniteLegale: "true" | "false";
    changementEconomieSocialeSolidaireUniteLegale: "true" | "false";
    changementEtatAdministratifUniteLegale: "true" | "false";
    changementNicSiegeUniteLegale: "true" | "false";
    changementNomUniteLegale: "true" | "false";
    changementNomUsageUniteLegale: "true" | "false";
    changementSocieteMissionUniteLegale: "true" | "false";
    dateDebut: string;
    dateFin: string;
    denominationUniteLegale: string;
    denominationUsuelle1UniteLegale: string;
    denominationUsuelle2UniteLegale: string;
    denominationUsuelle3UniteLegale: string;
    economieSocialeSolidaireUniteLegale: "O" | "N";
    etatAdministratifUniteLegale: "A" | "C";
    nicSiegeUniteLegale: string;
    nomenclatureActivitePrincipaleUniteLegale: string;
    nomUniteLegale: string;
    nomUsageUniteLegale: string;
    siren: string;
    societeMissionUniteLegale: "O" | "N";
}
