arrowParens: avoid
singleQuote: false
semi: true
trailingComma: all
printWidth: 120
bracketSameLine: true
htmlWhitespaceSensitivity: ignore
tabWidth: 4
plugins:
- prettier-plugin-svelte
svelteSortOrder: options-scripts-markup-styles
svelteStrictMode: false
svelteIndentScriptAndStyle: true
