import DEFAULT_ASSOCIATION from "../../../../../../../tests/__fixtures__/association.fixture";
import { SireneStockUniteLegaleEntity } from "../../../../../../entities/SireneStockUniteLegaleEntity";
import Siren from "../../../../../../identifier-objects/Siren";

export const STOCK_UNITE_LEGALE_ENTITY: SireneStockUniteLegaleEntity = {
    siren: new Siren(DEFAULT_ASSOCIATION.siren),
    statutDiffusionUniteLegale: "",
    unitePurgeeUniteLegale: "",
    dateCreationUniteLegale: "",
    sigleUniteLegale: "",
    sexeUniteLegale: "",
    prenom1UniteLegale: "",
    prenom2UniteLegale: "",
    prenom3UniteLegale: "",
    prenom4UniteLegale: "",
    prenomUsuelUniteLegale: "",
    pseudonymeUniteLegale: "",
    identifiantAssociationUniteLegale: "",
    trancheEffectifsUniteLegale: "",
    anneeEffectifsUniteLegale: "",
    dateDernierTraitementUniteLegale: "",
    nombrePeriodesUniteLegale: "",
    categorieEntreprise: "",
    anneeCategorieEntreprise: "",
    dateDebut: "",
    etatAdministratifUniteLegale: "",
    nomUniteLegale: "",
    nomUsageUniteLegale: "",
    denominationUniteLegale: "",
    denominationUsuelle1UniteLegale: "",
    denominationUsuelle2UniteLegale: "",
    denominationUsuelle3UniteLegale: "",
    categorieJuridiqueUniteLegale: "",
    activitePrincipaleUniteLegale: "",
    nomenclatureActivitePrincipaleUniteLegale: "",
    nicSiegeUniteLegale: DEFAULT_ASSOCIATION.nic,
    economieSocialeSolidaireUniteLegale: "",
    societeMissionUniteLegale: "",
    caractereEmployeurUniteLegale: "",
};
