export enum AgentTypeEnum {
    OPERATOR = "OPERATOR",
    CENTRAL_ADMIN = "CENTRAL_ADMIN",
    TERRITORIAL_COLLECTIVITY = "TERRITORIAL_COLLECTIVITY",
    DECONCENTRATED_ADMIN = "DECONCENTRATED_ADMIN",
}
