export enum AdminTerritorialLevel {
    REGIONAL = "REGIONAL",
    DEPARTMENTAL = "DEPARTMENTAL",
    INTERREGIONAL = "INTERREGIONAL",
    INTERDEPARTMENTAL = "INTERDEPARTMENTAL",
    OVERSEAS = "OVERSEAS",
}
