<!--Generated by https://betagouv.github.io/a11y-generateur-declaration/#create" -->

<h1>Déclaration d’accessibilité</h1>
<p>
    Établie le <span>15 novembre 2023</span>
    .
</p>
<p>
    <span>
        Direction de la jeunesse, de l'éducation populaire et de la vie associative (DJEPVA) - Ministère de l'Éducation
        nationale et de la Jeunesse
    </span>
    s’engage à rendre son service accessible, conformément à l’article 47 de la loi n° 2005-102 du 11 février 2005.
</p>
<p>
    Cette déclaration d’accessibilité s’applique à <strong>Data.Subvention</strong>
    <span>
        &nbsp(
        <span>https://app.datasubvention.beta.gouv.fr/</span>
        )
    </span>
    .
</p>
<h2>État de conformité</h2>
<p>
    <strong>Data.Subvention</strong>
    est
    <strong><span data-printfilter="lowercase">non conforme</span></strong>
    avec le
    <abbr title="Référentiel général d’amélioration de l’accessibilité">RGAA</abbr>
    .
    <span>Le site n’a encore pas été audité.</span>
</p>
<h2>Contenus non accessibles</h2>
<p>Les contenus listés ci-dessous ne sont pas accessibles pour les raisons suivantes.</p>
<h3>Non conformité</h3>
<p>
    Malgré nos efforts, certains contenus sont inaccessibles. Vous trouverez ci-dessous une liste des limitations
    connues et des solutions potentielles&nbsp;:
</p>
<ol class="technical-information accessibility-limitations">
    <li>
        <strong>La correspondance entre les subventions et les paiments dans le tableau de bord</strong>
        : La navigation au clavier parcourt toutes les subventions puis tous les paiments et perd donc l'information de correspondance
        parce que la structuration de nos données ne permet pas à ce jour de regrouper les informations en un seul tableau.
        Le design et la structuration des données sont en conception pour permettre de n'avoir qu'un seul tableau. Merci
        d’utiliser le formulaire de contact si vous rencontrez un problème.
    </li>
    <li>
        <strong>Focus après fermeture de la modale</strong>
        : Le focus est ramené au début de la page après fermeture d'une modale parce que notre composant modale est généralisé,
        et ne prend pas en compte les spécificités du contexte d'ouverture. Nous prévoyons de refactoriser ce composant.
    </li>
    <li>
        <strong>Structure de titres des cartes</strong>
        : Sur l'onglet "pièces administratives", les cartes présentent un mauvais niveau de titre parce que elles implémentent
        un composant dont le niveau de titre est figé et ne correspond pas au contexte d'appel. Nous refactoriserons ce composant
        pour rendre le niveau de titre adaptable.
    </li>
</ol>
<h2>Établissement de cette déclaration d’accessibilité</h2>
<p>
    Cette déclaration a été établie le <span>15 novembre 2023</span>
    .
</p>
<h3>Technologies utilisées</h3>
<p>
    L’accessibilité de <span>Data.Subvention</span>
    s’appuie sur les technologies suivantes&nbsp;:
</p>
<ul class="technical-information technologies-used">
    <li>HTML</li>
    <li>WAI-ARIA</li>
    <li>CSS</li>
</ul>
<h2>Amélioration et contact</h2>
<p>
    Si vous n’arrivez pas à accéder à un contenu ou à un service, vous pouvez contacter le responsable de <span>
        Data.Subvention
    </span>
    pour être orienté vers une alternative accessible ou obtenir le contenu sous une autre forme.
</p>
<ul class="basic-information feedback h-card">
    <li>
        Téléphone&nbsp;: <span>+33 4 51 22 01 35</span>
    </li>
    <li>
        E-mail&nbsp;: <a href="mailto:contact@datasubvention.beta.gouv.fr">contact@datasubvention.beta.gouv.fr</a>
    </li>

    <li>
        Formulaire de contact&nbsp;: <a href="https://datasubvention.beta.gouv.fr/contact/">
            https://datasubvention.beta.gouv.fr/contact/
        </a>
    </li>
    <li>
        Adresse&nbsp;: <span>DINUM, 20 avenue de Ségur, Paris 75007</span>
    </li>
    <li>
        LinkedIn : https://www.linkedin.com/company/data-subvention/
        <br />
        Crisp : https://datasubvention.crisp.help/fr/
    </li>
</ul>
<p>
    Nous essayons de répondre dans les <span>1 jour ouvré</span>
    .
</p>
<h2>Voie de recours</h2>
<p>
    Cette procédure est à utiliser dans le cas suivant&nbsp;: vous avez signalé au responsable du site internet un
    défaut d’accessibilité qui vous empêche d’accéder à un contenu ou à un des services du portail et vous n’avez pas
    obtenu de réponse satisfaisante.
</p>
<p>Vous pouvez&nbsp;:</p>
<ul>
    <li>
        Écrire un message au <a href="https://formulaire.defenseurdesdroits.fr/">Défenseur des droits</a>
    </li>
    <li>
        Contacter <a href="https://www.defenseurdesdroits.fr/saisir/delegues">
            le délégué du Défenseur des droits dans votre région
        </a>
    </li>
    <li>
        Envoyer un courrier par la poste (gratuit, ne pas mettre de timbre)&nbsp;:
        <br />
        Défenseur des droits
        <br />
        Libre réponse 71120 75342 Paris CEDEX 07
    </li>
</ul>
<hr />
<p>
    Cette déclaration d’accessibilité a été créé le <span>15 novembre 2023</span>
    grâce au
    <a href="https://betagouv.github.io/a11y-generateur-declaration/#create">
        Générateur de Déclaration d’Accessibilité de BetaGouv
    </a>
    .
</p>
