export default interface SireneUniteLegaleDto {
    siren: string;
    statutDiffusionUniteLegale: string;
    unitePurgeeUniteLegale: string | null | "";
    dateCreationUniteLegale: string;
    sigleUniteLegale: string | null | "";
    sexeUniteLegale: string | null | "";
    prenom1UniteLegale: string | null | "";
    prenom2UniteLegale: string | null | "";
    prenom3UniteLegale: string | null | "";
    prenom4UniteLegale: string | null | "";
    prenomUsuelUniteLegale: string | null | "";
    pseudonymeUniteLegale: string | null | "";
    identifiantAssociationUniteLegale: string | null;
    trancheEffectifsUniteLegale: string | null | "";
    anneeEffectifsUniteLegale: string | null;
    dateDernierTraitementUniteLegale: string | null | "";
    nombrePeriodesUniteLegale: string | null | "";
    categorieEntreprise: string | null | "";
    anneeCategorieEntreprise: string | null | "";
    dateDebut: string | null | "";
    etatAdministratifUniteLegale: string | null | "";
    nomUniteLegale: string | null | "";
    nomUsageUniteLegale: string | null | "";
    denominationUniteLegale: string | null | "";
    denominationUsuelle1UniteLegale: string | null | "";
    denominationUsuelle2UniteLegale: string | null | "";
    denominationUsuelle3UniteLegale: string | null | "";
    categorieJuridiqueUniteLegale: string;
    activitePrincipaleUniteLegale: string | null | "";
    nomenclatureActivitePrincipaleUniteLegale: string | null | "";
    nicSiegeUniteLegale: string | null | "";
    economieSocialeSolidaireUniteLegale: string | null | "";
    societeMissionUniteLegale: string | null | "";
    caractereEmployeurUniteLegale: string | null | "";
}
