import DEFAULT_ASSOCIATION from "../../../../../../tests/__fixtures__/association.fixture";
import { SireneUniteLegaleEntity } from "../../../../../entities/SireneUniteLegaleEntity";
import { Rna } from "../../../../../identifier-objects";
import Siren from "../../../../../identifier-objects/Siren";

export const STOCK_UNITE_LEGALE_ENTITY: SireneUniteLegaleEntity = {
    siren: new Siren(DEFAULT_ASSOCIATION.siren),
    statutDiffusionUniteLegale: null,
    unitePurgeeUniteLegale: null,
    dateCreationUniteLegale: new Date("1989-02-01T00:00:00.000Z"),
    sigleUniteLegale: null,
    sexeUniteLegale: null,
    prenom1UniteLegale: null,
    prenom2UniteLegale: null,
    prenom3UniteLegale: null,
    prenom4UniteLegale: null,
    prenomUsuelUniteLegale: null,
    pseudonymeUniteLegale: null,
    identifiantAssociationUniteLegale: new Rna(DEFAULT_ASSOCIATION.rna),
    trancheEffectifsUniteLegale: null,
    anneeEffectifsUniteLegale: null,
    dateDernierTraitementUniteLegale: new Date("2026-03-13T00:00:00.000Z"),
    nombrePeriodesUniteLegale: null,
    categorieEntreprise: null,
    anneeCategorieEntreprise: null,
    dateDebut: new Date("2022-01-01T00:00:00.000Z"),
    etatAdministratifUniteLegale: null,
    nomUniteLegale: null,
    nomUsageUniteLegale: null,
    denominationUniteLegale: DEFAULT_ASSOCIATION.name,
    denominationUsuelle1UniteLegale: null,
    denominationUsuelle2UniteLegale: null,
    denominationUsuelle3UniteLegale: null,
    categorieJuridiqueUniteLegale: "9220",
    activitePrincipaleUniteLegale: null,
    nomenclatureActivitePrincipaleUniteLegale: null,
    nicSiegeUniteLegale: DEFAULT_ASSOCIATION.nic,
    economieSocialeSolidaireUniteLegale: null,
    societeMissionUniteLegale: null,
    caractereEmployeurUniteLegale: null,
    activitePrincipaleNAF25UniteLegale: null,
};
