import MongoAdapter from "../MongoAdapter";
import { ChorusPaymentFlatEntity } from "../../../modules/providers/chorus/@types/ChorusPaymentFlat";
import Siren from "../../../identifierObjects/Siren";
import Siret from "../../../identifierObjects/Siret";
import { DefaultObject } from "../../../@types";
import PaymentFlatMapper from "../../../modules/paymentFlat/payment-flat.mapper";
import PaymentFlatEntity from "../../../entities/flats/PaymentFlatEntity";
import PaymentFlatDbo from "./PaymentFlatDbo";
import { PaymentFlatPort } from "./payment-flat.port";

// we omit _id because it is generated by MongoDB
export class PaymentFlatAdapter extends MongoAdapter<Omit<PaymentFlatDbo, "_id">> implements PaymentFlatPort {
    collectionName = "payments-flat";

    public async createIndexes(): Promise<void> {
        // use TS to avoid typo in index names
        const uniqueIdIndex: keyof PaymentFlatDbo = "idUnique";
        const idEstabIndex: keyof PaymentFlatDbo = "idEtablissementBeneficiaire";
        const typeIdEstabIndex: keyof PaymentFlatDbo = "typeIdEtablissementBeneficiaire";
        const idCompanyIndex: keyof PaymentFlatDbo = "idEntrepriseBeneficiaire";
        const typeIdCompanyIndex: keyof PaymentFlatDbo = "typeIdEntrepriseBeneficiaire";
        const budgetaryYear: keyof PaymentFlatDbo = "exerciceBudgetaire";
        const provider: keyof PaymentFlatDbo = "fournisseur";

        await this.collection.createIndex({ [uniqueIdIndex]: 1 }, { unique: true });
        await this.collection.createIndex({ [idEstabIndex]: 1, [typeIdEstabIndex]: 1 });
        await this.collection.createIndex({ [idCompanyIndex]: 1, [typeIdCompanyIndex]: 1 });
        await this.collection.createIndex({ [budgetaryYear]: 1 });
        await this.collection.createIndex({ [provider]: 1 });
    }

    public async hasBeenInitialized(): Promise<boolean> {
        const dbo = await this.collection.findOne({});
        return !!dbo;
    }

    public async insertOne(entity: PaymentFlatEntity): Promise<void> {
        await this.collection.insertOne(PaymentFlatMapper.toDbo(entity));
    }

    public async upsertOne(entity: PaymentFlatEntity): Promise<void> {
        const updateDbo = PaymentFlatMapper.toDbo(entity);
        await this.collection.updateOne({ idUnique: updateDbo.idUnique }, { $set: updateDbo }, { upsert: true });
    }

    private buildUpsertOperation(dbo: Omit<PaymentFlatDbo, "_id">) {
        return {
            updateOne: {
                filter: { idUnique: dbo.idUnique },
                update: { $set: dbo },
                upsert: true,
            },
        };
    }

    public upsertMany(entities: PaymentFlatEntity[]) {
        const bulk = entities.map(entity => this.buildUpsertOperation(PaymentFlatMapper.toDbo(entity)));
        return this.collection.bulkWrite(bulk, { ordered: false });
    }

    public async insertMany(entities: PaymentFlatEntity[]): Promise<void> {
        await this.collection.insertMany(entities.map(entity => PaymentFlatMapper.toDbo(entity), { ordered: false }));
    }

    // used in test
    public findAll(): Promise<PaymentFlatEntity[]> {
        return this.collection
            .find({})
            .map(dbo => PaymentFlatMapper.dboToEntity(dbo))
            .toArray();
    }

    public cursorFind(
        query: DefaultObject<unknown> = {},
        projection: DefaultObject<unknown> = {},
    ): AsyncIterable<PaymentFlatEntity> {
        return this.collection.find(query, projection).map(PaymentFlatMapper.dboToEntity);
    }

    public cursorFindChorusOnly(exerciceBudgetaire?: number): AsyncIterable<ChorusPaymentFlatEntity> {
        if (!exerciceBudgetaire) {
            return this.cursorFind({ fournisseur: "chorus" }) as AsyncIterable<ChorusPaymentFlatEntity>;
        } else
            return this.cursorFind({
                fournisseur: "chorus",
                exerciceBudgetaire: exerciceBudgetaire,
            }) as AsyncIterable<ChorusPaymentFlatEntity>;
    }

    public async deleteAll(): Promise<void> {
        await this.collection.deleteMany({});
    }

    public async findBySiret(siret: Siret): Promise<PaymentFlatEntity[]> {
        return this.collection
            .find({
                typeIdEtablissementBeneficiaire: siret.name,
                idEtablissementBeneficiaire: siret.value,
            })
            .map(PaymentFlatMapper.dboToEntity)
            .toArray();
    }

    public async findBySiren(siren: Siren): Promise<PaymentFlatEntity[]> {
        return this.collection
            .find({
                typeIdEntrepriseBeneficiaire: siren.name,
                idEntrepriseBeneficiaire: siren.value,
            })
            .map(PaymentFlatMapper.dboToEntity)
            .toArray();
    }

    public async findByEJ(ej: string): Promise<PaymentFlatEntity[]> {
        return this.collection.find({ ej: ej }).map(PaymentFlatMapper.dboToEntity).toArray();
    }
}

const paymentFlatAdapter = new PaymentFlatAdapter();
export default paymentFlatAdapter;
