env:
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "import"
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
ignorePatterns:
  - node_modules
rules:
  import/order: error
