env:
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - import
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
ignorePatterns:
  - node_modules
rules:
  import/order: error
