env:
  node: true
  es6: true
  browser: true
parser: "@typescript-eslint/parser"
plugins:
  - "import"
  - "jquery"
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
ignorePatterns:
  - node_modules
  - cleaned_modules
rules:
  import/order: error
  no-unused-vars:
    - "warn"
    -  destructuredArrayIgnorePattern: "^_"
